spring:
  datasource:
    url: ${props.db.url}
    username: ${props.db.username}
    password: ${props.db.password}

cors:
  enabled: ${props.cors.enabled}

mealplanner:
  app:
    jwtCookieName: ${props.app.jwtCookieName}
    jwtSecret: ${props.app.jwtSecret}
    jwtExpirationMs: ${props.app.jwtExpirationMs}