spring:
  datasource:
    url: ${props.db.url}
    username: ${props.db.username}
    password: ${props.db.password}

mealplanner:
  app:
    jwtSecret: ${props.app.jwtSecret}
    jwtExpirationMs: ${props.app.jwtExpirationMs}